/*Owner & Copyrights: Vance King Saxbe. A.*//*Copyright (c) <2014> Author Vance King Saxbe. A, and contributors Power Dominion Enterprise, Precieux Consulting and other contributors. Modelled, Architected and designed by Vance King Saxbe. A. with the geeks from GoldSax Consulting and GoldSax Technologies email @vsaxbe@yahoo.com. Development teams from Power Dominion Enterprise, Precieux Consulting. Project sponsored by GoldSax Foundation, GoldSax Group and executed by GoldSax Manager.*/

function str_compare($str1, $str2) {
    $count = 0;
    
    $str1 = ereg_replace("[^a-z]", ' ', strtolower($str1));
    while(strstr($str1, '  ')) {
        $str1 = str_replace('  ', ' ', $str1);
    }
    $str1 = explode(' ', $str1);
    
    $str2 = ereg_replace("[^a-z]", ' ', strtolower($str2));
    while(strstr($str2, '  ')) {
        $str2 = str_replace('  ', ' ', $str2);
    }
    $str2 = explode(' ', $str2);
    
    if(count($str1)<count($str2)) {
        $tmp = $str1;
        $str1 = $str2;
        $str2 = $tmp;
        unset($tmp);
    }
    
    for($i=0; $i<count($str1); $i++) {
        if(in_array($str1[$i], $str2)) {
            $count++;
        }
    }
    
    return $count/count($str2)*100;
}




// input misspelled word
$input = 'Icici';

// array of words to check against
$words  = array('ITCLTD','RELIANCE','INFOSYSLTD','HDFCBANKLT','HOUSINGDEVE','ICICIBANKL','TCSLTD','LARSENTOU','ONGCORPLTD','STATEBANKO','TATAMOTORS','HINDUNILT','BHARTIARTL','MAHINDRAM','TATASTL','AXISBANK','SUNPHARMACE','WIPROLTD','NTPCLTD','KOTAKBANK','BAJAJAUTO','DRREDDYSL','JINDALSTEEL','COALINDIA','HEROMOTOCO','NESTLELTD','ASIANPAINTS','BHEL','POWERGRID','MARUTISUZUK','CIPLALTD','GAILINDIA','ULTRATECHCM','STERLITEIN','GRASIMINDUS','INFRADEVFIN','TATAPOWER','HINDALCOIN','HCLTECHNO','LUPINLTD','BANKOFBARO','CAIRNIND','AMBUJACEME','ACCLTD','INDUSINDBK','BHARATPETRO','TITANIND','PUNJABNATBK','GLAXOSMITH','BOSCHLTD','COLGATEPALM','RANBAXYLABO','DLFLIMITED','YESBANK','SESAGOALTD','LICHFINAN','JAIPRAKASSO','ZEEENTER','NMDCLTD','FEDERALBANK','GLAXOSMICON','IDEACELL','JSWSL','ADANIENTER','INDIANOILC','GODREJCONS','DABURINDIA','RELINFRA','BANKOFINDI','CANARABANK','SHRIRAMTRAN','DivisLab','CUMMINSINDI','SIEMENSLTD','RECLTD','UNITDSPR','POWERFINAN','TATACHEMICA','ADANIPORTS','STEELAUTHOR','EXIDEINDUS','HINDUSTANPE','BAJHOLDINV','RPOWER','GLENMARKPHA','HINDZINC','CADILAHEALT','RELCOMLTD','UNIONBANK','CONTAINCORP','PIRAMAHEALT','INDIABULLS','CROMPTONGRE','BHARATFORGE','ADIBIRNUVO','MARICOLTD','TATAGLOBAL','APOLLOHOSE','UNITEDPHOSP','ORACLEFIN','BAJAJFINSE','OILINDIA','CASTROLINDI','UNITEDBREW','ABBLTD','PETRONETLNG','CRISILLTD','MMTCLTD','TORNTPOWER','RELIANCECAP','PIPAVAVDOC','IDBIBANKL','MAXINDIAL','JUBLFOOD','ADANIPOWER','ASHOKLEYLND','NHPC','BHUSHSTEEL','OPTOCIRCUIT','INDIANHOTEL','BRITANIAIN','ALLAHABADBK','UNITECHLTD','MMFINANSER','STRIDESARCO','INGVYSYABK','ORIENTALBK','MPHASISLTD','GREATEASTE','BATAINDILT','ANDHRABANK','PIDILITEIND','HEXAWARELTD','MRFLTD','DISHTV','COROMINTER','SOUTHINDIA','BHARATELECT','IFCILTD','EICHERMOTOR','IPCALABLTD','APOLLOTYRE','TECHMAH','NATALUMCO','GMRINFRASTR','MOTHSUMISY','VOLTASLTD','SHREECEMENT','WOCKHARDTLT','STANCHART','VIDEOCONIND','PROCTORGAMB','SUNTVNET','JAINIRRISY','EMAMILIMITE','JKBANK','RAJESHEXPOT','REDINGTON','THERMAXLMTD','OBEROIREAL','GUJPETRONET','GUJARATSTAT','AVENTISPHAR','HAVELLSINDIA','GODREJINDUS','SYNDICATE','MINDTREELTD','JSWENERGY','TRENT','WELCORP','COREEDUTEC','MADRASCEMNT','SUZLONENERGY','EIDPARRY','INDIACEMENT','SKFINDIA','AMTEKAUTOL','BIOCONLTD','PANTALRETAI','KANSAINERO','INDIANOVERS','CESCLTD','HOUSINGDEV','JINDALSAW','MCLEODRUSSE','TORRENTPHAR','GUJMINDEVL','EIHLIMITED','AUROBINDOPH','INDBULREAL','INFOEDGE','INDIANBANK','KPITCUMMIN','BLUECIRCLE','ENGINERIN','MANGALORERE','CENTURYTEXT','PAGEINDUSTR','TATACOMM','FINANCTECHN','MONNETISPA','JUBILANT','UCOBANK','INDRAGAS','KARNATAKABK','RAYMONDLTD','JPPOWER','CITYUNIONB','RUCHISOYA','GPPL','GUJARATFLUO','AIAENGINEER','SUPREMIND','GUJARATGAS','IRBINFRA','CHAMBALFERT','PTCINDIA','HATHWAYCAB','BALKRISHIND','CMCLTD','DENABANK','GITANJALIGE','FAGBEARING','BAJFINANCE','TUBEINVEST','EDELWEISS','JPINFRATEC','SOBHADEV','CENTRALBK','LAKSHMIMAW','NEYVELILIG','JAGRANPRAK','RALLIINDIA','VAKRANSOFTW','CORPORATION','MANAPFIN','MAHARASHSEA','AMARARAJA','VSTINDUSTRI','GILLETTEIND','SJVN','RENUKASUGAR','GODREJPROP','VIJAYABANK','ERAINFRA','HINDCOPPER','NIITTECHNO','SHRIRAMCITY','INDIABPOWER','AKZOINDIA','ARVINDLtd','IVRCLLTD','SADBHAVENGG','LNTFH','GODFREYPHIP','PFIZERLTD','BERGEPAINT','ALSTOMTD','ECLERX','TTKPRESTIG','INDINFOLINE','NAVBHARVEN','ESSAROILLT','DEWANHOUFI','AMTEKINDIL','3MINDIALTD','SHIPPINGCOR','INFOTECHENR','RADICOKHAIT','BEMLLTD','PUNJLLOYD','ALOKINDUSTR','SHOPPERSTOP','MCXLTD','BAYERCROP','PHOENIXMILL','GATEWAYDIST','BAJAJHINDLTD','ILFSTRANS','SINTEXINDUS','ABBOTTINDIA','BLUESTARL','GRUHFINANC','PERSISTENT','WYETHLTD','LANCOINFRA','COXKINGS','MOILLTD','ELGIEQUIP','BOMBAYDYEI','JSWISPAT','GVKPOWERINF','CARBOUNIVER','EDUCOMPSOLN','ALSTOMPROJE','GLODYNETECH','HTMEDIA','GREAVESCOTT','ICRA','BIRLACORPOR','ABANOFFSHO','KECINTERN','BALRAMPURC','JSL','SPICEJETLTD','BALLARPURIN','KIRLOILENG','DELTACORP','ESSARSHIP','BAJAJELECT','ABGSHIPYARD','FORTIS','WABCO','CHENNAIPETR','GUJNARMADA','HINDOILEXP','VATECHWABA','BLUEDARTEX','TATAINVCOR','BASFINDIA','HINDUSCONST','ROLTAIND','MUTHOOTFIN','DBREALTY','DEVCRBANK','GRAPHITINDI','SUNTECKREAL','TVSMOTORL','RELIGAREENT','DEEPAKFERT','RAINCOMMODI','SRFLIMITED','NCC','ORIENTPAPI','PARSVNATH','PRESTIGE','PRAJINDUSTR','UNICHEMLAB','WHIRLPOOLIN','CLARICHEM','TATACOFFEE','MAHINDRALIFE','MAHANAGTELE','SBKBIKANER','ZYLOGSYSTEM','STBKTRAVAN','KAJARIACERA','ANANTRAJIN','HIMFUTRCOM','VIPINDUSTRI','TATATELESRV','ORCHIDCHEM','GUJALKALI','PRISMCEMENT','FUTUREVENT','SUNDRAMFAST','STERTECH','NOVARTISIND','KEMROCINDE','POLARISFIN','BANKMAHA','KALPATPOWT','VARDHTEXT','DENNETWORK','DBCORP','JYOTHYLAB','SHREEGLOBAL','BOCINDIALT','JETAIRWAYS','MAGMAFIN','ALLCARGO','HSIL','AGROTECHF','SIMPLXINFRA','TECHNOELE','NAVNEETPUBL','FDCLIMITED','BFUTILITIES','ARSHYIAINTL','ESCORTSLTD','HCLINFOSYS','JKLAKSHMI','NIITLTD','GUJARANREC','MAHHOLIDAY','JBFINDLTD','USHAMARTIN','SREIINFRA','SUNPHAADV','ASTRAZENPHA','REIAGROLIM','DHANLAKBANK','KSKENERGY','TRIVENITURB','TAMILNADUNE','KFA','HONEYWELAUT','INGERSOLRND','A2ZMES','SKUMARNAT','ASAHIINDIA','SOLARIND','HOTELLEELAV','BGRENERGY','SMOBILITY','HEGLIMITED','FUTURECAP','UFLEXLTD','ZYDUSWELL','PIINDUSLTD','KIRLOSKARBR','KESORAMIND','TIMETECHNO','EROSMEDIA','SKSMICRO','OMAXELTD','PENLANDLTD','GAMMONINDI','TATAELXSI','BAJAJCORP','FINOLEXIND','SHIVVANIOIL','BALMERLAWRI','MONSANTOIND','NOIDATOLBR','NESCOLIMITD','GULFOILCOR','TULIPTELE','TV18BRDCST','THOMASCKIN','JMFINANCIAL','NITINFIRE','ONMOBILE','BOMBAYRAYON','MOTILALOFS','PUNJABNSIND','PRAKASHIND','TREEHOUSE','GTLINFRAST','RASHTRIYACH','TDPOWER','PATELENGINR','UNITEDBANK','RELINDLINF','ENTNETWORK','JAICORPLIM','VOLTAMPTRAN','MERCATOR','ELECONENGC','PRIMEFOCUS','POLYPLEXCOR','GEODLTD','JINDALSOUTH','ELECTROSTEL','SHREEASHTA','TIMKEMLT','ELDERPHARMA','KARUTURIGLO','SUJANATOWER','AQUALOGIST','ANSALINFRAS','UTTAMGALVA','KGNINDLTD','JBCHEMPHR','DECCANCHR','JYOTISTRUCT','JINDALPOLFM','APTECHLTD','BILCARELT','HIMADCHEMI','ANDHRPRPM','STATEBKMYS','NTWKMEDINV','KSOILSLTD','TITAGARHWAG','EVERONN','ADHUNIKMET','UNITEDBREWR','FKONCO','ESSDEEALUM','3IINFOTECH','LOVABLE','NATIONALFER','PURAVANKARA','MVLLIMITED','FSL','CMAHENDRA','GREATOFFSH','GTLLIMITED','KWADIAR(I)','SUBEXLTX','STTRADCORP','EVERESTKANT','PANACEABIOT','HMTLTD','SHREEGANESH','TRIVENIENGI','RELMEDIA','JAIBALAIND','ARSSINFRA');

// no shortest distance found, yet
$shortest = -1;
$rr = 0;
// loop through words to find the closest
foreach ($words as $word) {
$rr++;
similar_text($word, $input, $p); 
$jj[$rr][0] = $input;
$jj[$rr][1] = $word;
$jj[$rr][2] = $p;
$ff[$rr] = $p;
}


for($ii = 0; $ii <= $rr; $ii++ ) {
if( $jj[$ii][2] == max($ff) ) { 
echo $word;
}
}
?>/*email to provide support at vancekingsaxbe@powerdominionenterprise.com, businessaffairs@powerdominionenterprise.com, For donations please write to fundraising@powerdominionenterprise.com*/